version: '{build}'
image: Visual Studio 2017 Preview
configuration: Debug
platform: Any CPU
nuget:
  project_feed: true
artifacts:
  - path: src\SqLiteFileSystem\bin\**\*.nupkg
assembly_info:
  patch: false
before_build:
  - dotnet restore
  - ps:  $env:BUILD_VERSION = "build-" + [Int]::Parse($env:APPVEYOR_BUILD_NUMBER).ToString("000")
build_script:
  - dotnet build --version-suffix "%BUILD_VERSION%" --configuration "%CONFIGURATION%"
after_build:
  - cmd: ECHO dotnet pack --version-suffix "%BUILD_VERSION%" --configuration "%CONFIGURATION%"
  - cmd: dotnet pack --version-suffix "%BUILD_VERSION%" --configuration "%CONFIGURATION%" --no-build
test_script:
  # Appveyor logger crashes if used... so not logging test results to appveyor for now
  # Tests failing on release builds - test only on debug for now
  - dotnet test .\test\SqliteFileSystem.Tests\ --configuration "%CONFIGURATION%"
notifications:
- provider: Email
  to:
  - '{{commitAuthorEmail}}'
  on_build_success: true
  on_build_failure: true
  on_build_status_changed: true